config/routes.rb
Cipele46Web::Application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :users, controllers: { registrations: 'registrations', :omniauth_callbacks => 'users/omniauth_callbacks' }
  
  root :to => "ads#index"

  ActiveAdmin.routes(self)

  authenticated :user do
    root :to => 'ads#index'
  end
  get 'home' => 'ads#index'

  resources :ads do
    put :toggle
    put :close
    post :reply
    collection do
      get :my
    end
  end

  resource :user, :only => [:new, :show, :update]
  resources :regions, :only => [:index]
  resources :categories, :only => [:index, :show]
  resources :blog, :only => [:index, :show]

  mount Api::Base => "/api", as: "api"
end

app/models/ad.rb
class Ad < ActiveRecord::Base

  include Extensions::Ad::Expiration
  include Extensions::Ad::Type
  include Extensions::Ad::Status
  include Extensions::Ad::Delegation
  include Extensions::Ad::Searchable
  include Extensions::Ad::Pagination

  belongs_to :category
  belongs_to :user
  belongs_to :city
  has_many :favorites, :dependent => :destroy
  #has_many :replies, :dependent => :destroy

  attr_accessible :description, :status, :title, :ad_type, :category_id, :user_id, :city_id, :image, :phone,
    :email

  mount_uploader :image, ImageUploader

  scope :active, -> { where("ads.created_at >= :date", :date => VALID_FOR.days.ago).where(status: 2) }
  scope :closed, -> { where(status: 3) }
  scope :by_user_favorites, ->(user_id) { joins(:favorites).where("favorites.user_id = ?", user_id) }
  scope :supply, where(:ad_type => self.type[:supply])
  scope :demand, where(:ad_type => self.type[:demand])

  default_scope includes({ city: :region }, :category)
  
  validates :category_id, :presence => true
  validates :city_id, :presence => true
  validates :description, :presence => true
  validates :title, :presence => true
  validates :ad_type, :presence => true
  validate :phone_or_email_must_be_present

  def phone_or_email_must_be_present
    if !phone.present? && !email.present? then
      errors.add(:phone, "Obavezan je ili telefon ili email")
      errors.add(:email, "Obavezan je ili telefon ili email")
    end
  end
end

app/controllers/ads_controller.rb
# encoding: utf-8
class AdsController < ApplicationController
  before_filter :authenticate_user!, :except => [:show, :index, :reply]

  respond_to :html, :json

  def index
    @ads_search = @ad_filter.search
    @ads_without_category_id = @ad_filter.search_without(:category_id) 
    @ads_without_ad_type = @ad_filter.search_without(:ad_type) 
    @ads_without_region_id = @ad_filter.search_without(:region_id) 
    @ads_without_user_id = @ad_filter.search_without(:user_id)
    
    # to display breadcrumbs
    @ads_category = Category.find(@ad_filter.category_id) if @ad_filter.category_id != nil
    @ads_region   = Region.find(@ad_filter.region_id) if @ad_filter.region_id != nil
    @ads_type = @ad_filter.ad_type

    respond_with @ads = @ads_search.results
  end

  def show
    @ad = Ad.find(params[:id])
    respond_with @ad
  end

  def new
    @ad = current_user.ads.new
  end

  def create
    @ad = AdCreation.new.call :user => current_user, :params => params[:ad]
    respond_with @ad
  end

  def update
    @ad = current_user.ads.find(params[:id])
    @ad.update_attributes(params[:ad])
    respond_with @ad
  end

  def edit
    @ad = current_user.ads.find(params[:id])
    respond_with @ad
  end

  def destroy
    @ad = current_user.ads.find(params[:id])
    @ad.destroy
    respond_to do |format|
      format.html { redirect_to root_url, :notice => "Oglas obrisan" }
      format.json { render :nothing => true }
    end
  end

  def validate_content_and_email content, email
    if !email.present? then
      return "Obavezno je unjeti email za kontakt."
    elsif !email.match /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
      return "Email za kontakt je neispravan."
    end
    if !content.present? then
      return "Obavezno je unjeti tekst poruke."
    end
    return nil
  end

  def reply
    ad = Ad.find(params[:ad_id])
    content, email = params[:content], params[:email]

    error = validate_content_and_email content, email
    if error then
      flash[:error] = error
    elsif AdReplying.new.call ad: ad, content: content, email: email
      flash[:notice] = "Sent!"
    else
      flash[:error] = "Could't send you message."
    end

    if flash[:error] then
      redirect_to ad_path(ad, {:email => email, :content => content}), :error => flash[:error]
    else
      redirect_to ad_path(ad, {:email => email, :content => content}), :notice => flash[:notice]
    end
  end

  def toggle
    current_user.toggle_favorite @ad = Ad.find(params[:id])
    respond_with @ad
  end

  def close
    @ad = AdClosure.new.call :user => current_user, :id => params[:ad_id]
    respond_with @ad
  end
end

app/helpers/ads_helper.rb
module AdsHelper
  %w(region_id category_id ad_type user_id).each do |param|
    define_method("selected_#{param}") { params[param].to_i }
  end

  def image_tag_for_ad(ad, options = {})
    version = options[:version] || 'medium'
    image_tag ad.image_url, options.merge(:class => "")
  end
end

app/views/ads/_ad.html.erb
<article class="card <%= ad.type_name_css %>" data-details="<%= ad_path(ad) %>">
    <% if ad.image.present? %>
      <figure class="icon window-2">
      <%= link_to image_tag_for_ad(ad, :version => :small), ad_path(ad) %>
      </figure>
    <% end %>
    <h2><%= link_to ad.title, ad_path(ad) %></h2>
    <p><%= ad.description %></p>
    <footer>
        <span class="card-place icon stroke location"><%= ad.city.region.name %></span>
        <span class="card-category icon stroke category"><%= ad.category.name %></span>
        <span class="card-time icon stroke time"><%= time_ago_in_words ad.expires_at %></span>
        <% if current_user %>
          <% if ad_is_favorite(ad.id) %>
            <%= link_to "&#xE0B5;".html_safe, ad_toggle_path(ad.id), add: 'Dodaj u favorite', remove: 'Makni iz favorita', card: ad.id, :class => 'card-favorite selected hidden' %>
          <% else %>
            <%= link_to "&#xE49D;".html_safe, ad_toggle_path(ad.id), add: 'Dodaj u favorite', remove: 'Makni iz favorita', card: ad.id, :class => 'card-favorite hidden' %>
          <% end %>
        <% end %>

    </footer>
</article>

app/views/ads/_form.html.erb
<%= form_for @ad  do |f| %>


  <% ad_types_for_select.each do |key, value| %>
    <%= f.radio_button :ad_type, value, :id => "rdb-#{value}", :class => "radio", :checked => key == ad_types_for_select.keys.first  %>
    <%= f.label :ad_type, key.capitalize, :value => value, :id => key, :for => "rdb-#{value}" %>
  <% end %>

  <%= f.text_field :title, id: "naslov", placeholder: "Upišite naslov oglasa..." %> 
  <%= f.text_field :description, id: "tekst", placeholder: "Upišite tekst oglasa...", type: "textbox" %>

  <div class="inputArea">
    <div class="left">

      <%= f.label "Kategorija", class: "title" %>
      <div id="kategorija" class="dropdownSelect">
        <%= f.select :category_id, categories_for_select %></br>
      </div>

      <%= f.label "Grad", class: "title" %>
      <div id="grad" class="dropdownSelect">
        <%= f.select :city_id , grouped_options_for_select(cities_for_select) %>
      </div>

      <div class="input-container">
        <label> Kako bi vas zainteresirani mogli kontaktirati potrebno je ostaviti broj telefona ili email adresu. </label>
      </div>

      <div class="input-container">
        <%= f.label "Broj telefona/mobitela", class: "title" %>
        <%= f.text_field :phone, id: "telNum" %>
        <p>Biti će direktno vidljiv drugim korisnicima</p>
      </div>

      <div class="input-container">
        <%= f.label "Email adresa" %>
        <%= f.text_field :email, :hint => "Opcionalno, bit će javno prikazan uz oglas" %>
        <p>Neće biti direktno vidljiv drugim korisnicima</p>
      </div>
    </div>

    <div class="right">
      <label class="title">Dodajte fotografiju</label>
      <input id="uploadPhotoBtn" type="button">
      <%= f.file_field :image, id: "oglas_image", class: "file optional", style: "visibility:hidden;width:1px;height:1px" %>

      <div class="uploadingImg">
        <img id="uploadedImg" src="" type="file">
        <div class="bck"></div>
      </div>
    </div>
  </div>
  <%= f.submit "Rokaj", :class => "btn" if Rails.env.test? %>
<% end %>

app/views/ads/edit.html.erb
    <div class="page-content">
        <header class="page-content-header clearfix">
        </header>
        
        <section class="page-content-container clearfix">
          <%= render 'ads/form' %>
        </section>
    </div>

    <aside class="page-sidebar">
        <div class="logo" title="Cipele46">Cipele46</div>
        <p>Oglas će biti aktivan 30 dana od datuma objave. Prije objave administrator mora odobriti oglas. Hvala na strpljenju!</p>
        <%= link_to_function "Objavi oglas", "$('form').submit()", :class => "addButton" %>
        <%= link_to "Odustani", root_path, :class => "cancle" %>
    </aside>

app/views/ads/index.html.erb
<%= render 'application/left_navigation' %>

<div class="page-content">
    <header class="page-content-header clearfix">
      <%= render 'application/breadcrumbs' %>
      <div class="cards-counter clearfix">
        <strong><%= @ads_search.total %> </strong> <%= ads_plural @ads_search.total %>
      </div>
    </header>

    <section class="cards-board clearfix">
          <%= render @ads %>
    </section>

    <footer class="page-content-footer clearfix">
        <%= paginate @ads  %>
    </footer>
</div>

app/views/ads/new.html.erb
    <div class="page-content">
        <header class="page-content-header clearfix">
        </header>
        
        <section class="page-content-container clearfix">
          <%= render 'ads/form' %>
        </section>
    </div>

    <aside class="page-sidebar">
        <div class="logo" title="Cipele46">Cipele46</div>
        <p>Oglas će biti aktivan 30 dana od datuma objave. Prije objave administrator mora odobriti oglas. Hvala na strpljenju!</p>
        <%= link_to_function "Objavi oglas", "$('form#new_ad').submit()", :class => "addButton" %>
        <%= link_to "Odustani", root_path, :class => "cancle" %>
    </aside>

app/views/ads/show.html.erb
<div class="page-content-wrapper inner-page giving clearfix <%= @ad.type_name %>">

  <aside class="sidebar-wrapper">
    <% if @ad.user == current_user %>

      <div class="page-sidebar">
        <h3>Kontakt</h3>
          <% if @ad.phone != nil && @ad.phone.strip != "" %>
            <p class="sidebar-number"><%= @ad.phone %></p>
          <% end %>
          <% if @ad.email != nil && @ad.email.strip != "" %>
            <p class="sidebar-email"><%= @ad.email %></p>
          <% end %>
          <%= button_to "Uredi oglas", edit_ad_path(@ad), :class => 'sidebar-button', :id => "edit-ad", :method => :get %>
          <%= button_to "Zatvori oglas", ad_close_path(@ad), :class => 'sidebar-button', :id => "close-ad", :method => :put, :confirm => "Sigurno želite zatvoriti ovaj oglas?" %>
          <%= button_to "Obriši oglas", ad_path(@ad), :class => 'sidebar-button', :id => "delete-ad", :method => :delete, :confirm => "Sigurno želite obrisati ovaj oglas?" %>
      </div>

    <% else %>

      <div class="page-sidebar">
        <h3>Kontakt</h3>
        <% if @ad.phone != nil && @ad.phone.strip != "" %>
          <p class="sidebar-number"><%= @ad.phone %></p>
        <% end %>
        <%= button_tag "Pošalji upit", :id => "posalji_upit_button", :onclick => "$('#kontakt_form').removeClass('hidden'); $('#posalji_upit_button').addClass('hidden');", :class => "sidebar-button" %>
        <%= form_tag ad_reply_path(@ad), method: :post, :id => 'kontakt_form', :class => "hidden" do %>
          <p class="sidebar-input-description">Poruka</p> 
          <%= text_area_tag :content, params[:content], rows: "8", placeholder: "Upiši poruku"%>
          <p class="sidebar-input-description-email">Email adresa na koju želite dobiti odgovor</p>
          <%= text_field_tag :email, params[:email], placeholder: "Upiši email"%><br />
          <%= button_tag "Pošalji", :id => 'posalji_button', :onclick => "$('form').submit();", :class => 'sidebar-button'%>
        <% end %>
      </div>

    <% end %>
  </aside>

  <div class="page-content">
    <header class="page-content-header clearfix">
      <%= render 'application/breadcrumbs' %>
    </header>
    <section class="page-content-container clearfix">
      <article class="card-details">
        <header>
          <h2><%= @ad.title %></h2>
		      <span class="card-place icon stroke location"><%= link_to "#{@ad.city.region.name}", ads_path(:city_id => 0, :category_id => 0,:region_id => @ad.city.region.id) %>, <%= link_to "#{@ad.city.name}", ads_path(:city_id => @ad.city.id, :category_id => 0, :region_id => 0) %></span>
          <span class="card-category icon stroke category"><%= link_to "#{@ad.category.name}", ads_path(:category_id => @ad.category.id, :region_id => 0, :city_id => 0) %></span>
          <span class="card-time icon stroke time"><label><%= time_ago_in_words @ad.expires_at %></label></span>
          <% if current_user %>
            <% if ad_is_favorite(@ad.id) %>
              <%= link_to "&#xE0B5;".html_safe, ad_toggle_path(@ad.id), add: 'Dodaj u favorite', remove: 'Makni iz favorita', card: @ad.id, :class => 'card-favorite selected hidden' %>
            <% else %>
              <%= link_to "&#xE49D;".html_safe, ad_toggle_path(@ad.id), add: 'Dodaj u favorite', remove: 'Makni iz favorita', card: @ad.id, :class => 'card-favorite hidden' %>
            <% end %>
          <% end %>
        </header>
        <% if @ad.image.present? %>
          <figure class="icon window-2"><%= image_tag_for_ad @ad, :version => :medium %></figure>
        <% end %>
        <p><%= @ad.description %></p>
      </article>
    </section>
  </div>
</div>