config/routes.rb
Cipele46Web::Application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :users, controllers: { registrations: 'registrations', :omniauth_callbacks => 'users/omniauth_callbacks' }
  
  root :to => "ads#index"

  ActiveAdmin.routes(self)

  authenticated :user do
    root :to => 'ads#index'
  end
  get 'home' => 'ads#index'

  resources :ads do
    put :toggle
    put :close
    post :reply
    collection do
      get :my
    end
  end

  resource :user, :only => [:new, :show, :update]
  resources :regions, :only => [:index]
  resources :categories, :only => [:index, :show]
  resources :blog, :only => [:index, :show]

  mount Api::Base => "/api", as: "api"
end

app/models/blog.rb
class Blog < ActiveRecord::Base
  attr_accessible :content, :image, :title, :slug
  mount_uploader :image, BlogImageUploader
  validates :title, :presence => true

  extend FriendlyId
  friendly_id :title, use: :slugged

end

app/controllers/blog_controller.rb
class BlogController < ApplicationController

  def index
    @all_posts = Blog.select("slug, title").order("id desc")
    @main_posts = Blog.order("id desc").limit(5)
  end

  def show
    @post = Blog.find(params[:id])
    @site_title = @post.title
  end

end

app/helpers/blog_helper.rb
module BlogHelper
end

app/views/blog/index.html.erb
<aside class="sidebar-wrapper">
  <div class="page-sidebar">
    <h3>Arhiva</h3>
    <ul class="sidebar-blog-arhiva">
      <% @all_posts.each do |post| %>
      <li>
        <%= link_to post.title, blog_path(post) %>
      </li>
      <% end -%>
  </ul>
  </div>
</aside>

<div class="page-content blog">
  <header class="page-content-header clearfix">&nbsp;</header>
  <% @main_posts.each do |post| %>
  <section class="page-content-container clearfix">
    <article class="card-details formatted-user-input">
      <header>
        <h1><%= post.title %></h1>
        <span>Objavljeno <%= post.created_at.strftime("%d.%m.%Y") %></span>
      </header>
      <% if post.image.url %>
      <figure class="icon window-2"><%= image_tag post.image.url(:large) %></figure>
      <% end -%>
      <% unless post.content.blank? %>
      <p class="card-text"><%= HTML_Truncator.truncate(post.content, 20).html_safe %></p>
      <% end -%>
      <%= link_to "Više", blog_path(post), class: "link-vise" %>
    </article>
  </section>
  <% end %>
</div>

app/views/blog/show.html.erb
<aside class="sidebar-wrapper"></aside>
<div class="page-content">
  <header class="page-content-header clearfix">&nbsp;</header>
  <section class="page-content-container clearfix">
    <article class="card-details formatted-user-input">
      <header>
        <h1><%= @post.title %></h2>
        <span>Objavljeno <%= @post.created_at.strftime("%d.%m.%Y") %></span>
      </header>
      <% if @post.image.url %>
      <figure class="icon window-2"><%= image_tag @post.image.url(:large) %></figure>
      <% end -%>
      <p class="card-text"><%= @post.content.html_safe %></p>
    </article>
  </section>
</div>