config/routes.rb
Cipele46Web::Application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :users, controllers: { registrations: 'registrations', :omniauth_callbacks => 'users/omniauth_callbacks' }
  
  root :to => "ads#index"

  ActiveAdmin.routes(self)

  authenticated :user do
    root :to => 'ads#index'
  end
  get 'home' => 'ads#index'

  resources :ads do
    put :toggle
    put :close
    post :reply
    collection do
      get :my
    end
  end

  resource :user, :only => [:new, :show, :update]
  resources :regions, :only => [:index]
  resources :categories, :only => [:index, :show]
  resources :blog, :only => [:index, :show]

  mount Api::Base => "/api", as: "api"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  responders :json
  before_filter :prepare_filter

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_path, :alert => exception.message
  end

  private

    def prepare_filter
      @ad_filter = AdFilter.new(params)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def display_base_errors resource
    return '' if (resource.errors.empty?) or (resource.errors[:base].empty?)
    messages = resource.errors[:base].map { |msg| content_tag(:p, msg) }.join
    html = <<-HTML
    <div class="alert alert-error alert-block">
      <button type="button" class="close" data-dismiss="alert">&#215;</button>
      #{messages}
    </div>
    HTML
    html.html_safe
  end

  def number_of_ads_in(facet, value = nil)
    instance_variable_get("@ads_without_#{facet}").facet(facet).rows.select{ |row| row.value == value || value == nil }.sum{ |row| row.count } || 0
  end

  def ads_plural(ads_count)
    ads_count = ads_count.to_s
    if ads_count[ads_count.size-1,ads_count.size] == '1' && ads_count[ads_count.size-2,ads_count.size] != '11'  && ads_count[ads_count.size-2,ads_count.size] != '111'  && ads_count[ads_count.size-2,ads_count.size] != '1111' && ads_count[ads_count.size-2,ads_count.size] != '11111'
      'oglas'
    else
      'oglasa'
    end
  end

  def ad_is_favorite(ad_id)
    current_user.favorite_ads.map(&:id).include?(ad_id) ? true : false
  end

  def align_footer
    if current_page?(root_path)
      "align"
    end
  end

  def body_id
    if rendering_ad_form? then "addPage"
    else "page"
    end
  end

  def wrapper_class
    klass = "page-content-wrapper clearfix"
    klass << " inner-page blog giving" if rendering_blog?
    klass << " inner-page" if rendering_ad_form?
    klass
  end

  private

    def rendering_ad_form?
      controller_name == "ads" && ["new","edit","create", "update"].include?(action_name)
    end

    def rendering_blog?
      controller_name == "blog"
    end
end

app/views/application/_breadcrumbs.html.erb
      <ul class="breadcrumbs clearfix">
      	<% if @ad != nil then %>
	        <li><%= link_to @ad.category.name, ads_path(:category_id => @ad.category.id) %></li>
	        <li><%= link_to @ad.city.region.name, ads_path(:region_id => @ad.city.region.id) %></li>
        <% else %>
	        <% if @ads_type != nil then %>
	        	<li><%= link_to Ad::humanized_type.invert[@ads_type].capitalize, ads_path(:ad_type => @ads_type) %></li>
	        <% end %>
        	<% if @ads_category != nil then %>
	        	<li><%= link_to @ads_category.name, ads_path(:category_id => @ads_category.id) %></li>
	        <% end %>
	        <% if @ads_region != nil then %>
	        	<li><%= link_to @ads_region.name, ads_path(:region_id => @ads_region.id) %></li>
	        <% end %>
        <% end %>
      </ul>

app/views/application/_flash_messages.html.erb
<% flash.each do |name, msg| %>
  <div id="flash_<%=name%>" class="flash-message clearfix">
    <div class="inner"><%= msg %> </div>
  </div>
<% end %>

app/views/application/_footer.html.erb
<footer class="page-footer <%= align_footer %>">
  <div class="space"></div>
  <p class="host-info"> Hosted by <%= link_to "Plus.hr", "http://plus.hr" %></p>
</footer>

app/views/application/_left_navigation.html.erb
<script type="text/javascript">
  $(function() {
    $("aside a.filter-action").click(function(e) {
      e.preventDefault();
      var query = $.deserialize(URI($(this).attr("href")).query());
      for(var key in query) {
        console.log(key);
        console.log(query[key]);
        $("form#filter_form").find("[name=" + key + "]").val(query[key]);
      }
      $("form#filter_form").submit();
    });
  });
</script>
<aside class="page-sidebar">
  <nav class="cards-board-filter">
    <ul id="cards-board-filter-nav">
        <% if current_user %>
        <li class="expanded">
          <a href="javascript:void(null)">Moj kutak</a>
          <ul>
            <li class="<%= selected_user_id == 0 ? 'current' : '' %>">
              <%= link_to "Svi oglasi (#{number_of_ads_in(:user_id)})", ads_path(user_id: 0), class: 'filter-action' %> 
            </li>
            <li class="<%= selected_user_id == current_user.id ? 'current' : '' %>">
              <%= link_to "Moji oglasi (#{number_of_ads_in(:user_id, current_user.id)})", ads_path(user_id: current_user.id), class: 'filter-action' %> 
            </li>
          </ul>
        </li>
        <% end -%>
        <li class="expanded">
            <a href="javascript:void(null)">Vrsta oglasa</a>
            <ul>
                <li class="all <%=[Ad.type[:supply], Ad.type[:demand]].include?(selected_ad_type) ? 
                  '' : 'current'%>">
                  <%= link_to "Svi oglasi (#{number_of_ads_in(:ad_type)})", ads_path(:ad_type => 0), class: 'filter-action' %>          
                </li>

                <li class="giving <%= selected_ad_type == Ad.type[:supply] ? 'current': ''%>">
                  <%= link_to "Poklanjam (#{number_of_ads_in(:ad_type, Ad.type[:supply])})", ads_path(:ad_type => Ad.type[:supply]), class: 'filter-action' %>
                </li>

                <li class="receiving <%= selected_ad_type == Ad.type[:demand] ? 'current': ''%>">
                  <%= link_to "Trebam (#{number_of_ads_in(:ad_type, Ad.type[:demand])})", ads_path(:ad_type => Ad.type[:demand]), class: 'filter-action' %>
                </li>
            </ul>
        </li>
        <li class="expanded">
            <a href="javascript:void(null)">Kategorije</a>
            <ul>
                <li class="<%= selected_category_id == 0 ? 'current' : ''%>">
                  <%= link_to "Sve kategorije (#{number_of_ads_in(:category_id)})", ads_path(category_id: 0), class: 'filter-action' %>
                </li>
                <% Category.scoped.each do |category| %>
                  <li class="<%= selected_category_id == category.id ? 'current' : ''%>">
                    <%= link_to "#{category.name} (#{number_of_ads_in(:category_id, category.id)})", 
                      ads_path(category_id: category.id), class: 'filter-action' %>
                  </li>
                <% end -%>
            </ul>
        </li>
        <li class="expanded">
            <a href="javascript:void(null)">Županije</a>
            <ul>
                <li class="<%= selected_region_id == 0 ? 'current' : ''%>">
                  <%= link_to "Sve županije (#{number_of_ads_in(:region_id)})", ads_path(region_id: 0), class: 'filter-action' %>
                </li>
                <% Region.scoped.each do |region| %>
                  <li class="<%= selected_region_id == region.id ? 'current' : '' %>">
                    <%= link_to "#{region.name} (#{number_of_ads_in(:region_id, region.id)})", 
                      ads_path(region_id: region.id), class: 'filter-action' %>
                  </li>
                <% end -%>
            </ul>
        </li>
    </ul>
  </nav>
</aside>

app/views/application/_new_add_button.html.erb
<% if current_user && ["ads/new", "ads/create"].include?("#{controller_name}/#{action_name}") %>
  <%# Do not show button in header when posting new ad %>  
<% elsif current_user %>  
  <%= link_to "Objavi oglas", new_ad_path %>
<% else %>
  <%= link_to "Objavi oglas", new_user_session_path %>
<% end -%>

app/views/application/_top_navigation.html.erb
<header class="page-header">
  <div class="page-header-inner-wrapper clearfix">
    <%= link_to "Cipele46", root_path, { class: Rails.env == 'staging' ? 'logo logo-staging' : 'logo', title: 'Cipele46' } %>
    <nav>
      <%= main_menu %>
    </nav>
    <div id="search">
      <%= form_tag(ads_path, method: :get, id: :filter_form) do %>
        <%= hidden_field_tag :user_id, @ad_filter.user_id %>
        <%= hidden_field_tag :category_id, @ad_filter.category_id %>
        <%= hidden_field_tag :region_id, @ad_filter.region_id %>
        <%= hidden_field_tag :ad_type, @ad_filter.ad_type %>
        <%= text_field_tag :query, @ad_filter.query, title: :search, placeholder: 'pretraži' %>
        <%= button_tag '', id: 'search-button', title: 'Search', name: nil %>
      <% end %>
    </div>
    <ul class="nav-user">
        <li class="nav-user-new-add">
          <%= render 'application/new_add_button' %>
        </li>
        <% unless current_user %>
        <li class="nav-user-not-logged">
          <%= link_to "Prijavi se", new_user_session_path %>
        </li>
        <% end -%>
        <% if current_user %>
        <li class="nav-user-settings">
            <%= link_to current_user.name, edit_user_registration_path %>
            <div>
              <ul>
                <li><%= link_to "Postavke", edit_user_registration_path %></li>
                <li><%= link_to 'Moji oglasi', ads_path(user_id: current_user.id) %></li>
                <li><%= link_to "Odjavi se", destroy_user_session_path, { id: "sign-out", method: 'DELETE' } %></li>
              </ul>
            <div>
        </li>
        <% end -%>
    </ul>
  </div>
</header>